export const markerImages = {
  bar: require('../assets/images/map-icons/icon-bar.png'),
  water: require('../assets/images/map-icons/icon-water.png'),
  camping: require('../assets/images/map-icons/icon-camping.png'),
  douche: require('../assets/images/map-icons/icon-douche.png'),
  ehbo: require('../assets/images/map-icons/icon-ehbo.png'),
  eten: require('../assets/images/map-icons/icon-eten.png'),
  fuiftent: require('../assets/images/map-icons/icon-fuiftent.png'),
  infopunt: require('../assets/images/map-icons/icon-infopunt.png'),
  kampvuur: require('../assets/images/map-icons/icon-kampvuur.png'),
  markt: require('../assets/images/map-icons/icon-markt.png'),
  piscine: require('../assets/images/map-icons/icon-piscine.png'),
  podium: require('../assets/images/map-icons/icon-podium.png'),
  rookzone: require('../assets/images/map-icons/icon-rookzone.png'),
  rustigeBar: require('../assets/images/map-icons/icon-rustige-bar.png'),
  wc: require('../assets/images/map-icons/icon-wc.png'),
};
