allowBuilds:
  '@sentry/cli': true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.22'
  - expo-modules-core@57.0.16
  - expo-modules-jsi@57.0.8
  - expo@57.0.20
  - '@expo/ui@57.0.16'
  - expo-insights@57.0.16
  - expo-notifications@57.0.17
  - expo-router@57.0.19
onlyBuiltDependencies:
  - '@sentry/cli'

overrides:
  '@expo/metro-runtime': '^57.0.12'
