name: Expo Publish
on:
  push:
    branches:
      - master
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    outputs:
      semVer: ${{steps.gitversion.outputs.semVer}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '5.x'
      - uses: gittools/actions/gitversion/execute@v3.0.0
        id: gitversion
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{steps.gitversion.outputs.semVer}}"
          message: "v${{steps.gitversion.outputs.semVer}}"
  staging:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: [version]
    env:
      SEMVER: ${{needs.version.outputs.semVer}}
      CI: 1
      EXPO_PUBLIC_CONTENT_ROOT: Staging
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install --immutable
      - run: eas update --branch staging --message ${{env.SEMVER}}
  production:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: [staging, version]
    env:
      SEMVER: ${{needs.version.outputs.semVer}}
      CI: 1
      EXPPO_PUBLIC_CONTENT_ROOT: Production
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - uses: expo/expo-github-action@v6
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install --immutable
      - run: eas update --branch production --message ${{env.SEMVER}} && npx sentry-expo-upload-sourcemaps dist
