# This is a basic workflow to help you get started with Actions

name: PR validation

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    -  uses: gittools/actions/gitversion/execute@v0.9.8
    -  uses: gittools/actions/gitversion/setup@v0.9.8
       with:
         versionSpec: '5.x'
    - run: yarn install
    - run: yarn run lint
