# This is a basic workflow to help you get started with Actions

name: PR validation

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: 20.x
    -  uses: gittools/actions/gitversion/setup@v3.0.0
       with:
         versionSpec: '5.x'
    -  uses: gittools/actions/gitversion/execute@v3.0.0
    - run: yarn install
    - run: yarn run lint
