name: EAS Build
on: workflow_dispatch
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_CONTENT_ROOT: Production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '5.x'
      - uses: gittools/actions/gitversion/execute@v3.0.0
        id: gitversion
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["app.config.ts"]'
        env:
          APP_VERSION: ${{steps.gitversion.outputs.semVer}}
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate licenses.json
        run: yarn generate-licenses
      - name: Build on EAS
        run: eas build --platform all --non-interactive --no-wait